afet-yonetim-sistemi/ays-fe-landing

src/Page/Main.jsx
src/Styles.css
src/helper/language.js

fix : language option select button edited

---

src/index.css

feat: reducing the page in size

---

CODEOWNERS
src/Page/Main.jsx
src/Styles.css

fix: Production revizes

---

src/Page/Main.jsx
src/Styles.css
src/helper/language.js

fix: Production texts changed

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE.md
SECURITY.md

feat: Improvements to the GitHub Community Standards

---

src/Page/Main.jsx

feat: Linkedin account icon added

---

package.json
src/Page/Main.jsx

fix: contact info svg made wrapperable

---

public/index.html

feat: improvement on site description

---

ISSUE_TEMPLATE.md
PR_TEMPLATE.md
README.md
package-lock.json

closed #1 
Issue Template konusunda pek örnek bulamadım, birden fazla dosya şeklinde düzenlendiğini ve her konunun alt başlıklarla ISSUE_TEMPLATE klasörü altında barındırıldığını gördüm. Düzenlenilmesi istenirse o formata geçirilebilir, örneğinin görselini aşağıya bırakıyor olacağım.

feat: github comminity standarts Issue and PR template 

---

src/Styles.css
src/helper/language.js

-------
##Before
-----
##After
-------

AYS-17 feat: intro section introduction descriptions have been updated

---

src/Page/Main.jsx
src/Styles.css
src/helper/language.js

AYS-87 ana ekranda bulunan hangi teknolojileri kullaniyoruz bolumu altindaki product basliginin GitHub projects den jiraya guncellenmesi

---

src/Page/Main.jsx
src/Styles.css

##Expected
-------
Sol görsel header kısmını sağ görsel footer kısmını göstermekte beklenen linklerin çalışır durumda olup kullanıcıyı jiraya yönlendirmesidir. 
##Before
-------
##After
-------

AYS-22 jira ve confluence icon ve baglanti linklerinin ana sayfaya eklenmesi

---

components.json
package-lock.json
package.json
src/app/globals.css
src/app/page.tsx
src/components/ui/button.tsx
src/lib/providers.tsx
src/lib/utils.ts
tailwind.config.ts

This pull request replaces the Ant Design library in the Disaster Management System project with Shadcn UI. With this change, UI components and style usage have been updated in accordance with Shadcn UI.
- Removed the Ant Design library.
- Integrated the Shadcn UI library into the project.
- Refactored UI components to use Shadcn UI components and styles.
- Ensured compatibility with Shadcn UI's design principles.
- Added new tests to validate the changes.
- Updated existing tests to ensure compatibility with Shadcn UI.
**Related Issue:**
[#AYS-277](https://afetyonetimsistemi.atlassian.net/browse/AYS-277)

AYS-277 | Replacing Ant Design library with Shadcn UI

---

CODEOWNERS
package-lock.json
package.json
src/app/globals.css
src/app/layout.tsx
src/app/page.tsx
src/components/ui/toast/toast.tsx
src/components/ui/toast/toaster.tsx
src/components/ui/toast/use-toast.ts
tailwind.config.ts

-  **Change Type:**
-  **Summary:**
- Shadcn Toast package added
- Created success theme color for Tailwind
- Added 'success' variant in Shadcn UI
- Added 3 buttons on the homepage for testing notifications
- Necessary documentation has been added or …

AYS-252 | Preparation of Action Feedback Infrastructure

---

CONTRIBUTING.md

- Added Development Standards to Contributing.md
- …

AYS-312 | Add Development Standards to CONTRIBUTING.md

---

src/app/globals.css
src/components/AboutUs/index.tsx
src/components/Container.tsx
src/components/EmergencyForm/index.tsx
src/components/EmergencyInfo/index.tsx
src/components/Footer/index.tsx
src/components/Header/DrawerNav.tsx
src/components/Header/HeaderNav.tsx
src/components/Header/HeaderTop.tsx
src/components/Header/index.tsx
src/components/Hero/HeroCarousel.tsx
src/components/main.tsx
src/i18n/locales/tr.json

- Correction of typos noted by the test team, some minimisation of the header, reduction of x-axis spacing inside the container
- Default reviewers have been assigned to …

AYS-10 | Landing page revision

---

.github/dependabot.yml
.github/workflows/application-health-checker.yml
.github/workflows/pull-request-checker.yml
.gitignore
README.md

- Assignees have been added if necessary.
- No specific actions are required in the Labels and Associations …

AYS-356 | GitHub Actions Have Been Integrated as `pull-request-checker` and `application-health-checker`

---

src/app/globals.css
src/components/SocialIcons.tsx

- Changed the navbar social icon colors
- Assignees …

AYS-369 | Changed the navbar social icon colors

---

src/app/globals.css
src/components/SocialIcons.tsx

- X icon added to both footer and header | quick fix on global.css line 44, added semicolon instead of comma on the end of the line
- Necessary documentation has been added or existing documentation …

AYS-370 | X icon added to both footer and header / quick fix on global.css

---

README.md

- update readme with useful lint and format commands
- [ x] **Documentation:**
- Default reviewers have been …

AYS-397 | update readme for eslint rules

---

src/lib/handleApiError.ts
src/services/formService.ts
src/utils/errorHandler.ts

- Add a short description (e.g., added or modified features).
- Default reviewers have been assigned to this pull …

AYS 471 | error handle for too many requests

---

package.json
src/components/EmergencyForm/schema/formSchema.ts

- add validation to check phone line number to be 10 digits
- Default reviewers have been assigned to this pull …

AYS-504 | Phone Format Validation

---

src/components/EmergencyForm/schema/formSchema.ts

- update regex 
- Assignees have been added if …

AYS-504 | update regex of string fields

---

src/components/EmergencyForm/schema/formSchema.ts

- Added int check
- Assignees have been added if …

AYS-480 | fix seating count validation

---

.github/workflows/application-health-checker.yml
.github/workflows/pull-request-checker.yml
sonar-project.properties

- SonarQube integration
- Assignees have been added …

AYS-573 | SonarQube Integration

---

src/components/EmergencyForm/EvacuationForm.tsx
src/components/SelectLocation.tsx

- Disable Selecting Same City/District
- Assignees …

AYS-524 | Disable Selecting Same City/District

---

LICENSE.md
SECURITY.md

- Update License and Security Files with iletisim@afetyonetimsistemi.org
- Default reviewers have been assigned …

AYS-782 | Update License and Security Files

---

package-lock.json
package.json
src/components/SocialIcons.tsx
src/components/ui/tooltip.tsx

- Add Tooltip to Social Media Icons and Add Slack Icon
- Default reviewers have been assigned to this pull …

AYS-794 | Add Tooltip to Social Media Icons and Add Slack Icon

---

package-lock.json
package.json
src/components/EmergencyForm/EvacuationForm.tsx
src/components/EmergencyForm/ProxyEvacuationForm.tsx
src/components/EmergencyForm/schema/formSchema.ts
src/components/ui/PhoneInput.tsx
src/utils/errorHandler.ts

- added phone number validation disabled country selection
- Default reviewers have been assigned to this pull …

AYS-747 | change phonenumber validations to google lib

---

src/components/EmergencyForm/EvacuationForm.tsx

- renamed targetcity and seatingcount
- Assignees …

AYS-831 | Evacuation Application Form Name Updates

---

package-lock.json
src/components/EmergencyForm/EvacuationForm.tsx
src/components/EmergencyForm/ProxyEvacuationForm.tsx
src/components/EmergencyForm/SelfEvacuationForm.tsx
src/components/EmergencyForm/schema/formSchema.ts
src/components/NumericInput.tsx

- Assignees have been added if necessary.
- No specific actions are required in the Labels and Associations …

AYS-480 | `NumericInput` Component Has Been Created and Used In Emergency Evacuation Application Form

---

src/components/EmergencyForm/schema/formSchema.ts

- changed 12 to 10
- Assignees have been added if …

AYS-747 | change validation message

---

CODEOWNERS

- Assignees have been added if necessary.
- No …

`CODEOWNERS` File Has Been Updated

---

src/configs/axiosConfig.ts
src/services/formService.ts

- Assignees have been added if necessary.
- No …

AYS-875 | New `/api/landing/v1/**` Base Path Has Been Defined
